services:
  - type: web
    name: video-annotator
    runtime: python
    region: oregon
    buildCommand: |
      sudo apt-get update && sudo apt-get install -y libgl1 libglib2.0-0 ffmpeg
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true